[target.thumbv6m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m0 -machine microbit -nographic -semihosting-config enable=on,target=native -kernel"
rustflags = ["-C", "link-arg=-Tlink.x"]

[build]
target = "thumbv6m-none-eabi"
